### PR TITLE
CanBuildFrom: Add support for Class and simple form for To (fix #135)

### LINKED ISSUE #135: Rewrite CanBuildFrom => Factory from a class
https://github.com/akka/akka/blob/131e6d10d63fb4aa293d9eb54b58d4f74f5ddee9/akka-stream/src/main/scala/akka/stream/impl/Sinks.scala#L268-L309

```scala
@InternalApi private[akka] final class SeqStage[T, That](implicit cbf: CanBuildFrom[Nothing, T, That with immutable.Traversable[_]]) extends GraphStageWithMaterializedValue[SinkShape[T], Future[That]] {
  val in = Inlet[T]("seq.in")

  override def toString: String = "SeqStage"

  override val shape: SinkShape[T] = SinkShape.of(in)

  override protected def initialAttributes: Attributes = DefaultAttributes.seqSink

  override def createLogicAndMaterializedValue(inheritedAttributes: Attributes) = {
    val p: Promise[That] = Promise()
    val logic = new GraphStageLogic(shape) with InHandler {
      val buf = cbf()

      override def preStart(): Unit = pull(in)

      def onPush(): Unit = {
        buf += grab(in)
        pull(in)
      }

      override def onUpstreamFinish(): Unit = {
        val result = buf.result()
        p.trySuccess(result)
        completeStage()
      }

      override def onUpstreamFailure(ex: Throwable): Unit = {
        p.tryFailure(ex)
        failStage(ex)
      }

      override def postStop(): Unit = {
        if (!p.isCompleted) p.failure(new AbruptStageTerminationException(this))
      }

      setHandler(in, this)
    }

    (logic, p.future)
  }
}
```

https://github.com/akka/akka/blob/131e6d10d63fb4aa293d9eb54b58d4f74f5ddee9/akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala#L236-L248
```scala
  def collection[T, That](implicit cbf: CanBuildFrom[Nothing, T, That with immutable.Traversable[_]]): Sink[T, Future[That]] =
    Sink.fromGraph(new SeqStage[T, That])
```

expected:

```scala
@InternalApi private[akka] final class SeqStage[T, That](implicit cbf: Factory[T, That with immutable.Traversable[_]]) extends GraphStageWithMaterializedValue[SinkShape[T], Future[That]] {
```

```scala
@InternalApi private[akka] final class SeqStage[T, That](implicit cbf: Factory[T, That with immutable.Traversable[_]]) extends GraphStageWithMaterializedValue[SinkShape[T], Future[That]] {
  val in = Inlet[T]("seq.in")

  override def toString: String = "SeqStage"

  override val shape: SinkShape[T] = SinkShape.of(in)

  override protected def initialAttributes: Attributes = DefaultAttributes.seqSink

  override def createLogicAndMaterializedValue(inheritedAttributes: Attributes) = {
    val p: Promise[That] = Promise()
    val logic = new GraphStageLogic(shape) with InHandler {
      val buf = cbf.newBuilder

      override def preStart(): Unit = pull(in)

      def onPush(): Unit = {
        buf += grab(in)
        pull(in)
      }

      override def onUpstreamFinish(): Unit = {
        val result = buf.result()
        p.trySuccess(result)
        completeStage()
      }

      override def onUpstreamFailure(ex: Throwable): Unit = {
        p.tryFailure(ex)
        failStage(ex)
      }

      override def postStop(): Unit = {
        if (!p.isCompleted) p.failure(new AbruptStageTerminationException(this))
      }

      setHandler(in, this)
    }

    (logic, p.future)
  }
}
```

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

File: scalafix/input/src/main/scala/fix/CanBuildFromSrc.scala [hunk 1]
```diff
@@ -33,4 +33,11 @@ object CanBuildFromSrc {
     cbf2("")
     ()
   }
+
+  def f2[T, That](implicit cbf: CanBuildFrom[Nothing, T, That]): Foo[T, That] =
```
Comment (MasseGuillaume) [inline scalafix/input/src/main/scala/fix/CanBuildFromSrc.scala]: Previously it would only take `CanBuildFrom[Nothing, A, CC[B]]` now it accepts `CanBuildFrom[Nothing, A, B]`, but it won't rewrite `e.to[CC] => cbf.fromSpecific(e)`

File: scalafix/input/src/main/scala/fix/CanBuildFromSrc.scala [hunk 2]
```diff
@@ -33,4 +33,11 @@ object CanBuildFromSrc {
...
+    new Foo
+
+  class Foo[T, That](implicit cbf: CanBuildFrom[Nothing, T, That]) {
```
Comment (MasseGuillaume) [inline scalafix/input/src/main/scala/fix/CanBuildFromSrc.scala]: We now support Classes and Def. I don't see another place where we could insert a CanBuildFrom. Maybe on a type alias (`type  Foo = CanBuildFrom[Bar, Buz, Qux]`)?
